[mongodb]
mongodb-dev.kcdevops.online

[catalogue]
catalogue-dev.kcdevops.online

[redis]
redis-dev.kcdevops.online

[user]
user-dev.kcdevops.online

[cart]
cart-dev.kcdevops.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.kcdevops.online
CATALOGUE_HOST=catalogue-dev.kcdevops.online
REDIS_HOST= redis-dev.kcdevops.online
USER_HOST= user-dev.kcdevops.online


