- name: create ec2 and route53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-0cecc7f37156227f4
    ami_id: ami-0220d79f3f480ecf5
    domain_name: kcdevops.online
    env: dev
    instances:
    - mongodb
    - catalogue
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      #key_name: "{{ key_name }}"
      instance_type: "t3.micro"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ env }}"
      tags:
        project: roboshop
        component: "{{ item }}"
        Environment: "{{ env }}"
        Name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  - name: create route53 records
    amazon.aws.route53:
      state: present
      overwrite: true
      zone: "{{ domain_name }}"
      record: "{{ item.item }}-{{ env }}.{{ domain_name }}" #mongodb-dev.kcdevops.online, frontend-dev.kcdevops.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
    loop: "{{ ec2_output.results }}"
  
  - name: create public IP route53 records
    amazon.aws.route53:
      state: present
      overwrite: true
      zone: "{{ domain_name }}"
      record: "roboshop-{{ env }}.{{ domain_name }}" #roboshop-dev.kcdevops.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
    loop: "{{ ec2_output.results }}"
    when: item.item == 'frontend'